#############################################################################
# Makefile for building: basic_graph
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  basic_graph.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile basic_graph.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I/usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = basic_graph1.0.0
DISTDIR = /users/3/310/Bobrovnikov_MR/graph_qt5/.tmp/basic_graph1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so /usr/lib64/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		approximator.cpp \
		window.cpp moc_window.cpp
OBJECTS       = main.o \
		approximator.o \
		window.o \
		moc_window.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		basic_graph.pro window.h \
		approximator.h \
		graphMethod.h main.cpp \
		approximator.cpp \
		window.cpp
QMAKE_TARGET  = basic_graph
DESTDIR       = 
TARGET        = basic_graph


first: all
####### Build rules

basic_graph:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: basic_graph.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		basic_graph.pro
	$(QMAKE) -o Makefile basic_graph.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
basic_graph.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile basic_graph.pro

qmake_all: FORCE


all: Makefile basic_graph

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents window.h approximator.h graphMethod.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp approximator.cpp window.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp
moc_window.cpp: window.h \
		/usr/include/qt5/QtWidgets/QtWidgets \
		/usr/include/qt5/QtWidgets/QtWidgetsDepends \
		/usr/include/qt5/QtCore/QtCore \
		/usr/include/qt5/QtCore/QtCoreDepends \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qconfig-64.h \
		/usr/include/qt5/QtCore/qtcore-config.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qnumeric.h \
		/usr/include/qt5/QtCore/qversiontagging.h \
		/usr/include/qt5/QtCore/qabstractanimation.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringliteral.h \
		/usr/include/qt5/QtCore/qstringalgorithms.h \
		/usr/include/qt5/QtCore/qstringview.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qhashfunctions.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qbytearraylist.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qabstracteventdispatcher.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qabstractnativeeventfilter.h \
		/usr/include/qt5/QtCore/qabstractproxymodel.h \
		/usr/include/qt5/QtCore/qabstractstate.h \
		/usr/include/qt5/QtCore/qabstracttransition.h \
		/usr/include/qt5/QtCore/qanimationgroup.h \
		/usr/include/qt5/QtCore/qarraydataops.h \
		/usr/include/qt5/QtCore/qarraydatapointer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/qbitarray.h \
		/usr/include/qt5/QtCore/qbuffer.h \
		/usr/include/qt5/QtCore/qbytearraymatcher.h \
		/usr/include/qt5/QtCore/qcache.h \
		/usr/include/qt5/QtCore/qcborarray.h \
		/usr/include/qt5/QtCore/qcborvalue.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtCore/qcborcommon.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/quuid.h \
		/usr/include/qt5/QtCore/qcbormap.h \
		/usr/include/qt5/QtCore/qcborstream.h \
		/usr/include/qt5/QtCore/qfloat16.h \
		/usr/include/qt5/QtCore/qcollator.h \
		/usr/include/qt5/QtCore/qcommandlineoption.h \
		/usr/include/qt5/QtCore/qcommandlineparser.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qdeadlinetimer.h \
		/usr/include/qt5/QtCore/qelapsedtimer.h \
		/usr/include/qt5/QtCore/qdir.h \
		/usr/include/qt5/QtCore/qfileinfo.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtCore/qdiriterator.h \
		/usr/include/qt5/QtCore/qeasingcurve.h \
		/usr/include/qt5/QtCore/qendian.h \
		/usr/include/qt5/QtCore/qeventtransition.h \
		/usr/include/qt5/QtCore/qexception.h \
		/usr/include/qt5/QtCore/qfactoryinterface.h \
		/usr/include/qt5/QtCore/qfileselector.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QStringList \
		/usr/include/qt5/QtCore/qfilesystemwatcher.h \
		/usr/include/qt5/QtCore/qfinalstate.h \
		/usr/include/qt5/QtCore/qfuture.h \
		/usr/include/qt5/QtCore/qfutureinterface.h \
		/usr/include/qt5/QtCore/qrunnable.h \
		/usr/include/qt5/QtCore/qresultstore.h \
		/usr/include/qt5/QtCore/qfuturesynchronizer.h \
		/usr/include/qt5/QtCore/qfuturewatcher.h \
		/usr/include/qt5/QtCore/qhistorystate.h \
		/usr/include/qt5/QtCore/qidentityproxymodel.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtCore/qjsonarray.h \
		/usr/include/qt5/QtCore/qjsonvalue.h \
		/usr/include/qt5/QtCore/qjsondocument.h \
		/usr/include/qt5/QtCore/qjsonobject.h \
		/usr/include/qt5/QtCore/qlibrary.h \
		/usr/include/qt5/QtCore/qlibraryinfo.h \
		/usr/include/qt5/QtCore/qversionnumber.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtCore/qlinkedlist.h \
		/usr/include/qt5/QtCore/qlockfile.h \
		/usr/include/qt5/QtCore/qloggingcategory.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qmath.h \
		/usr/include/qt5/QtCore/qmessageauthenticationcode.h \
		/usr/include/qt5/QtCore/qmetaobject.h \
		/usr/include/qt5/QtCore/qmimedata.h \
		/usr/include/qt5/QtCore/qmimedatabase.h \
		/usr/include/qt5/QtCore/qmimetype.h \
		/usr/include/qt5/QtCore/qobjectcleanuphandler.h \
		/usr/include/qt5/QtCore/qoperatingsystemversion.h \
		/usr/include/qt5/QtCore/qparallelanimationgroup.h \
		/usr/include/qt5/QtCore/qpauseanimation.h \
		/usr/include/qt5/QtCore/qplugin.h \
		/usr/include/qt5/QtCore/qpointer.h \
		/usr/include/qt5/QtCore/qpluginloader.h \
		/usr/include/qt5/QtCore/qprocess.h \
		/usr/include/qt5/QtCore/qpropertyanimation.h \
		/usr/include/qt5/QtCore/qvariantanimation.h \
		/usr/include/qt5/QtCore/qqueue.h \
		/usr/include/qt5/QtCore/qrandom.h \
		/usr/include/qt5/QtCore/qreadwritelock.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qresource.h \
		/usr/include/qt5/QtCore/qsavefile.h \
		/usr/include/qt5/QtCore/qscopedvaluerollback.h \
		/usr/include/qt5/QtCore/qscopeguard.h \
		/usr/include/qt5/QtCore/qsemaphore.h \
		/usr/include/qt5/QtCore/qsequentialanimationgroup.h \
		/usr/include/qt5/QtCore/qsettings.h \
		/usr/include/qt5/QtCore/qsharedmemory.h \
		/usr/include/qt5/QtCore/qsignalmapper.h \
		/usr/include/qt5/QtCore/qsignaltransition.h \
		/usr/include/qt5/QtCore/qsocketnotifier.h \
		/usr/include/qt5/QtCore/qsortfilterproxymodel.h \
		/usr/include/qt5/QtCore/qstack.h \
		/usr/include/qt5/QtCore/qstandardpaths.h \
		/usr/include/qt5/QtCore/qstate.h \
		/usr/include/qt5/QtCore/qstatemachine.h \
		/usr/include/qt5/QtCore/qstorageinfo.h \
		/usr/include/qt5/QtCore/qstringlistmodel.h \
		/usr/include/qt5/QtCore/qsystemsemaphore.h \
		/usr/include/qt5/QtCore/qtemporarydir.h \
		/usr/include/qt5/QtCore/qtemporaryfile.h \
		/usr/include/qt5/QtCore/qtextboundaryfinder.h \
		/usr/include/qt5/QtCore/qtextcodec.h \
		/usr/include/qt5/QtCore/qthread.h \
		/usr/include/qt5/QtCore/qthreadpool.h \
		/usr/include/qt5/QtCore/qthreadstorage.h \
		/usr/include/qt5/QtCore/qtimeline.h \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qtimezone.h \
		/usr/include/qt5/QtCore/qtranslator.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qwaitcondition.h \
		/usr/include/qt5/QtCore/qwineventnotifier.h \
		/usr/include/qt5/QtCore/qxmlstream.h \
		/usr/include/qt5/QtCore/qtcoreversion.h \
		/usr/include/qt5/QtGui/QtGui \
		/usr/include/qt5/QtGui/QtGuiDepends \
		/usr/include/qt5/QtGui/qtguiglobal.h \
		/usr/include/qt5/QtGui/qtgui-config.h \
		/usr/include/qt5/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt5/QtGui/qtextlayout.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtGui/qrgba64.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpixelformat.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/include/qt5/QtGui/qglyphrun.h \
		/usr/include/qt5/QtGui/qrawfont.h \
		/usr/include/qt5/QtGui/qfontdatabase.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextdocument.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qaccessible.h \
		/usr/include/qt5/QtGui/qaccessiblebridge.h \
		/usr/include/qt5/QtGui/qaccessibleobject.h \
		/usr/include/qt5/QtGui/qaccessibleplugin.h \
		/usr/include/qt5/QtGui/qbackingstore.h \
		/usr/include/qt5/QtGui/qwindow.h \
		/usr/include/qt5/QtCore/QEvent \
		/usr/include/qt5/QtCore/QMargins \
		/usr/include/qt5/QtCore/QRect \
		/usr/include/qt5/QtGui/qsurface.h \
		/usr/include/qt5/QtGui/qsurfaceformat.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qbitmap.h \
		/usr/include/qt5/QtGui/qclipboard.h \
		/usr/include/qt5/QtGui/qdesktopservices.h \
		/usr/include/qt5/QtGui/qdrag.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qgenericmatrix.h \
		/usr/include/qt5/QtGui/qgenericplugin.h \
		/usr/include/qt5/QtGui/qgenericpluginfactory.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtGui/qiconengine.h \
		/usr/include/qt5/QtGui/qiconengineplugin.h \
		/usr/include/qt5/QtGui/qimageiohandler.h \
		/usr/include/qt5/QtGui/qimagereader.h \
		/usr/include/qt5/QtGui/qimagewriter.h \
		/usr/include/qt5/QtGui/qmatrix4x4.h \
		/usr/include/qt5/QtGui/qvector3d.h \
		/usr/include/qt5/QtGui/qvector4d.h \
		/usr/include/qt5/QtGui/qquaternion.h \
		/usr/include/qt5/QtGui/qmovie.h \
		/usr/include/qt5/QtGui/qoffscreensurface.h \
		/usr/include/qt5/QtGui/qopengl.h \
		/usr/include/qt5/QtCore/qt_windows.h \
		/usr/include/qt5/QtGui/qopengles2ext.h \
		/usr/include/qt5/QtGui/qopenglext.h \
		/usr/include/qt5/QtGui/qopenglbuffer.h \
		/usr/include/qt5/QtGui/qopenglcontext.h \
		/usr/include/qt5/QtCore/QScopedPointer \
		/usr/include/qt5/QtGui/QSurfaceFormat \
		/usr/include/qt5/QtGui/qopenglversionfunctions.h \
		/usr/include/qt5/QtGui/qopengldebug.h \
		/usr/include/qt5/QtGui/qopenglextrafunctions.h \
		/usr/include/qt5/QtGui/qopenglfunctions.h \
		/usr/include/qt5/QtGui/qopenglframebufferobject.h \
		/usr/include/qt5/QtGui/qopenglpaintdevice.h \
		/usr/include/qt5/QtGui/qopenglpixeltransferoptions.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtGui/qopenglshaderprogram.h \
		/usr/include/qt5/QtGui/qopengltexture.h \
		/usr/include/qt5/QtGui/qopengltextureblitter.h \
		/usr/include/qt5/QtGui/QMatrix3x3 \
		/usr/include/qt5/QtGui/QMatrix4x4 \
		/usr/include/qt5/QtGui/qopengltimerquery.h \
		/usr/include/qt5/QtGui/qopenglvertexarrayobject.h \
		/usr/include/qt5/QtGui/qopenglwindow.h \
		/usr/include/qt5/QtGui/QPaintDeviceWindow \
		/usr/include/qt5/QtGui/qpaintdevicewindow.h \
		/usr/include/qt5/QtGui/QWindow \
		/usr/include/qt5/QtGui/QPaintDevice \
		/usr/include/qt5/QtGui/QOpenGLContext \
		/usr/include/qt5/QtGui/QImage \
		/usr/include/qt5/QtGui/qpagedpaintdevice.h \
		/usr/include/qt5/QtGui/qpagelayout.h \
		/usr/include/qt5/QtGui/qpagesize.h \
		/usr/include/qt5/QtGui/qpaintengine.h \
		/usr/include/qt5/QtGui/qpainter.h \
		/usr/include/qt5/QtGui/qpdfwriter.h \
		/usr/include/qt5/QtGui/qpicture.h \
		/usr/include/qt5/QtGui/qpictureformatplugin.h \
		/usr/include/qt5/QtGui/qpixmapcache.h \
		/usr/include/qt5/QtGui/qrasterwindow.h \
		/usr/include/qt5/QtGui/qscreen.h \
		/usr/include/qt5/QtCore/QList \
		/usr/include/qt5/QtCore/QSize \
		/usr/include/qt5/QtCore/QSizeF \
		/usr/include/qt5/QtGui/QTransform \
		/usr/include/qt5/QtGui/qsessionmanager.h \
		/usr/include/qt5/QtGui/qstandarditemmodel.h \
		/usr/include/qt5/QtGui/qstatictext.h \
		/usr/include/qt5/QtGui/qstylehints.h \
		/usr/include/qt5/QtGui/qsyntaxhighlighter.h \
		/usr/include/qt5/QtGui/qtextobject.h \
		/usr/include/qt5/QtGui/qtextdocumentfragment.h \
		/usr/include/qt5/QtGui/qtextdocumentwriter.h \
		/usr/include/qt5/QtGui/qtextlist.h \
		/usr/include/qt5/QtGui/qtexttable.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtGui/qtguiversion.h \
		/usr/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtWidgets/qaccessiblewidget.h \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/qcalendarwidget.h \
		/usr/include/qt5/QtWidgets/qcheckbox.h \
		/usr/include/qt5/QtWidgets/qcolordialog.h \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/qcolormap.h \
		/usr/include/qt5/QtWidgets/qcolumnview.h \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qcommandlinkbutton.h \
		/usr/include/qt5/QtWidgets/qpushbutton.h \
		/usr/include/qt5/QtWidgets/qcommonstyle.h \
		/usr/include/qt5/QtWidgets/qcompleter.h \
		/usr/include/qt5/QtWidgets/qdatawidgetmapper.h \
		/usr/include/qt5/QtWidgets/qdatetimeedit.h \
		/usr/include/qt5/QtWidgets/qdial.h \
		/usr/include/qt5/QtWidgets/qdialogbuttonbox.h \
		/usr/include/qt5/QtWidgets/qdirmodel.h \
		/usr/include/qt5/QtWidgets/qfileiconprovider.h \
		/usr/include/qt5/QtWidgets/qdockwidget.h \
		/usr/include/qt5/QtWidgets/qdrawutil.h \
		/usr/include/qt5/QtWidgets/qerrormessage.h \
		/usr/include/qt5/QtWidgets/qfiledialog.h \
		/usr/include/qt5/QtWidgets/qfilesystemmodel.h \
		/usr/include/qt5/QtWidgets/qfocusframe.h \
		/usr/include/qt5/QtWidgets/qfontcombobox.h \
		/usr/include/qt5/QtWidgets/qfontdialog.h \
		/usr/include/qt5/QtWidgets/qformlayout.h \
		/usr/include/qt5/QtWidgets/QLayout \
		/usr/include/qt5/QtWidgets/qgesture.h \
		/usr/include/qt5/QtWidgets/qgesturerecognizer.h \
		/usr/include/qt5/QtWidgets/qgraphicsanchorlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsitem.h \
		/usr/include/qt5/QtWidgets/qgraphicslayout.h \
		/usr/include/qt5/QtWidgets/qgraphicslayoutitem.h \
		/usr/include/qt5/QtWidgets/qgraphicseffect.h \
		/usr/include/qt5/QtWidgets/qgraphicsgridlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsitemanimation.h \
		/usr/include/qt5/QtWidgets/qgraphicslinearlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsproxywidget.h \
		/usr/include/qt5/QtWidgets/qgraphicswidget.h \
		/usr/include/qt5/QtWidgets/qgraphicsscene.h \
		/usr/include/qt5/QtWidgets/qgraphicssceneevent.h \
		/usr/include/qt5/QtWidgets/qgraphicstransform.h \
		/usr/include/qt5/QtGui/QVector3D \
		/usr/include/qt5/QtWidgets/qgraphicsview.h \
		/usr/include/qt5/QtWidgets/qscrollarea.h \
		/usr/include/qt5/QtWidgets/qgroupbox.h \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qinputdialog.h \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtWidgets/qitemdelegate.h \
		/usr/include/qt5/QtWidgets/qitemeditorfactory.h \
		/usr/include/qt5/QtWidgets/qkeyeventtransition.h \
		/usr/include/qt5/QtWidgets/qkeysequenceedit.h \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qlcdnumber.h \
		/usr/include/qt5/QtWidgets/qlistview.h \
		/usr/include/qt5/QtWidgets/qlistwidget.h \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qmdiarea.h \
		/usr/include/qt5/QtWidgets/qmdisubwindow.h \
		/usr/include/qt5/QtWidgets/qmenu.h \
		/usr/include/qt5/QtWidgets/qmenubar.h \
		/usr/include/qt5/QtWidgets/qmessagebox.h \
		/usr/include/qt5/QtWidgets/qmouseeventtransition.h \
		/usr/include/qt5/QtWidgets/qopenglwidget.h \
		/usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qplaintextedit.h \
		/usr/include/qt5/QtWidgets/qtextedit.h \
		/usr/include/qt5/QtWidgets/qprogressbar.h \
		/usr/include/qt5/QtWidgets/qprogressdialog.h \
		/usr/include/qt5/QtWidgets/qproxystyle.h \
		/usr/include/qt5/QtWidgets/QCommonStyle \
		/usr/include/qt5/QtWidgets/qradiobutton.h \
		/usr/include/qt5/QtWidgets/qscrollbar.h \
		/usr/include/qt5/QtWidgets/qscroller.h \
		/usr/include/qt5/QtCore/QPointF \
		/usr/include/qt5/QtWidgets/QScrollerProperties \
		/usr/include/qt5/QtWidgets/qscrollerproperties.h \
		/usr/include/qt5/QtCore/QMetaType \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/qshortcut.h \
		/usr/include/qt5/QtWidgets/qsizegrip.h \
		/usr/include/qt5/QtWidgets/qspinbox.h \
		/usr/include/qt5/QtWidgets/qsplashscreen.h \
		/usr/include/qt5/QtWidgets/qsplitter.h \
		/usr/include/qt5/QtWidgets/qstackedlayout.h \
		/usr/include/qt5/QtWidgets/qstackedwidget.h \
		/usr/include/qt5/QtWidgets/qstatusbar.h \
		/usr/include/qt5/QtWidgets/qstyleditemdelegate.h \
		/usr/include/qt5/QtWidgets/qstylefactory.h \
		/usr/include/qt5/QtWidgets/qstylepainter.h \
		/usr/include/qt5/QtWidgets/qstyleplugin.h \
		/usr/include/qt5/QtWidgets/qsystemtrayicon.h \
		/usr/include/qt5/QtWidgets/qtableview.h \
		/usr/include/qt5/QtWidgets/qtablewidget.h \
		/usr/include/qt5/QtWidgets/qtextbrowser.h \
		/usr/include/qt5/QtWidgets/qtoolbar.h \
		/usr/include/qt5/QtWidgets/qtoolbox.h \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/qtooltip.h \
		/usr/include/qt5/QtWidgets/qtreeview.h \
		/usr/include/qt5/QtWidgets/qtreewidget.h \
		/usr/include/qt5/QtWidgets/qtreewidgetitemiterator.h \
		/usr/include/qt5/QtWidgets/qundogroup.h \
		/usr/include/qt5/QtWidgets/qundostack.h \
		/usr/include/qt5/QtWidgets/qundoview.h \
		/usr/include/qt5/QtWidgets/qwhatsthis.h \
		/usr/include/qt5/QtWidgets/qwidgetaction.h \
		/usr/include/qt5/QtWidgets/qwizard.h \
		/usr/include/qt5/QtWidgets/qtwidgetsversion.h \
		graphMethod.h \
		approximator.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /users/3/310/Bobrovnikov_MR/graph_qt5/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/users/3/310/Bobrovnikov_MR/graph_qt5 -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include' -I'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include' -I'C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt' -I'C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt' window.h -o moc_window.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/qt5/QtGui/qtguiglobal.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qconfig-64.h \
		/usr/include/qt5/QtCore/qtcore-config.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qnumeric.h \
		/usr/include/qt5/QtCore/qversiontagging.h \
		/usr/include/qt5/QtGui/qtgui-config.h \
		/usr/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringliteral.h \
		/usr/include/qt5/QtCore/qstringalgorithms.h \
		/usr/include/qt5/QtCore/qstringview.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qhashfunctions.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qbytearraylist.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtGui/qrgba64.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixelformat.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QMainWindow \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/QVBoxLayout \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QMenuBar \
		/usr/include/qt5/QtWidgets/qmenubar.h \
		/usr/include/qt5/QtWidgets/qmenu.h \
		/usr/include/qt5/QtWidgets/QMessageBox \
		/usr/include/qt5/QtWidgets/qmessagebox.h \
		/usr/include/qt5/QtWidgets/qdialog.h \
		window.h \
		/usr/include/qt5/QtWidgets/QtWidgets \
		/usr/include/qt5/QtWidgets/QtWidgetsDepends \
		/usr/include/qt5/QtCore/QtCore \
		/usr/include/qt5/QtCore/QtCoreDepends \
		/usr/include/qt5/QtCore/qabstractanimation.h \
		/usr/include/qt5/QtCore/qabstracteventdispatcher.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtCore/qabstractnativeeventfilter.h \
		/usr/include/qt5/QtCore/qabstractproxymodel.h \
		/usr/include/qt5/QtCore/qabstractstate.h \
		/usr/include/qt5/QtCore/qabstracttransition.h \
		/usr/include/qt5/QtCore/qanimationgroup.h \
		/usr/include/qt5/QtCore/qarraydataops.h \
		/usr/include/qt5/QtCore/qarraydatapointer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/qbitarray.h \
		/usr/include/qt5/QtCore/qbuffer.h \
		/usr/include/qt5/QtCore/qbytearraymatcher.h \
		/usr/include/qt5/QtCore/qcache.h \
		/usr/include/qt5/QtCore/qcborarray.h \
		/usr/include/qt5/QtCore/qcborvalue.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtCore/qcborcommon.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtCore/quuid.h \
		/usr/include/qt5/QtCore/qcbormap.h \
		/usr/include/qt5/QtCore/qcborstream.h \
		/usr/include/qt5/QtCore/qfloat16.h \
		/usr/include/qt5/QtCore/qcollator.h \
		/usr/include/qt5/QtCore/qcommandlineoption.h \
		/usr/include/qt5/QtCore/qcommandlineparser.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdeadlinetimer.h \
		/usr/include/qt5/QtCore/qelapsedtimer.h \
		/usr/include/qt5/QtCore/qdir.h \
		/usr/include/qt5/QtCore/qfileinfo.h \
		/usr/include/qt5/QtCore/qdiriterator.h \
		/usr/include/qt5/QtCore/qeasingcurve.h \
		/usr/include/qt5/QtCore/qendian.h \
		/usr/include/qt5/QtCore/qeventtransition.h \
		/usr/include/qt5/QtCore/qexception.h \
		/usr/include/qt5/QtCore/qfactoryinterface.h \
		/usr/include/qt5/QtCore/qfileselector.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QStringList \
		/usr/include/qt5/QtCore/qfilesystemwatcher.h \
		/usr/include/qt5/QtCore/qfinalstate.h \
		/usr/include/qt5/QtCore/qfuture.h \
		/usr/include/qt5/QtCore/qfutureinterface.h \
		/usr/include/qt5/QtCore/qrunnable.h \
		/usr/include/qt5/QtCore/qresultstore.h \
		/usr/include/qt5/QtCore/qfuturesynchronizer.h \
		/usr/include/qt5/QtCore/qfuturewatcher.h \
		/usr/include/qt5/QtCore/qhistorystate.h \
		/usr/include/qt5/QtCore/qidentityproxymodel.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtCore/qjsonarray.h \
		/usr/include/qt5/QtCore/qjsonvalue.h \
		/usr/include/qt5/QtCore/qjsondocument.h \
		/usr/include/qt5/QtCore/qjsonobject.h \
		/usr/include/qt5/QtCore/qlibrary.h \
		/usr/include/qt5/QtCore/qlibraryinfo.h \
		/usr/include/qt5/QtCore/qversionnumber.h \
		/usr/include/qt5/QtCore/qlinkedlist.h \
		/usr/include/qt5/QtCore/qlockfile.h \
		/usr/include/qt5/QtCore/qloggingcategory.h \
		/usr/include/qt5/QtCore/qmath.h \
		/usr/include/qt5/QtCore/qmessageauthenticationcode.h \
		/usr/include/qt5/QtCore/qmetaobject.h \
		/usr/include/qt5/QtCore/qmimedata.h \
		/usr/include/qt5/QtCore/qmimedatabase.h \
		/usr/include/qt5/QtCore/qmimetype.h \
		/usr/include/qt5/QtCore/qobjectcleanuphandler.h \
		/usr/include/qt5/QtCore/qoperatingsystemversion.h \
		/usr/include/qt5/QtCore/qparallelanimationgroup.h \
		/usr/include/qt5/QtCore/qpauseanimation.h \
		/usr/include/qt5/QtCore/qplugin.h \
		/usr/include/qt5/QtCore/qpointer.h \
		/usr/include/qt5/QtCore/qpluginloader.h \
		/usr/include/qt5/QtCore/qprocess.h \
		/usr/include/qt5/QtCore/qpropertyanimation.h \
		/usr/include/qt5/QtCore/qvariantanimation.h \
		/usr/include/qt5/QtCore/qqueue.h \
		/usr/include/qt5/QtCore/qrandom.h \
		/usr/include/qt5/QtCore/qreadwritelock.h \
		/usr/include/qt5/QtCore/qresource.h \
		/usr/include/qt5/QtCore/qsavefile.h \
		/usr/include/qt5/QtCore/qscopedvaluerollback.h \
		/usr/include/qt5/QtCore/qscopeguard.h \
		/usr/include/qt5/QtCore/qsemaphore.h \
		/usr/include/qt5/QtCore/qsequentialanimationgroup.h \
		/usr/include/qt5/QtCore/qsettings.h \
		/usr/include/qt5/QtCore/qsharedmemory.h \
		/usr/include/qt5/QtCore/qsignalmapper.h \
		/usr/include/qt5/QtCore/qsignaltransition.h \
		/usr/include/qt5/QtCore/qsocketnotifier.h \
		/usr/include/qt5/QtCore/qsortfilterproxymodel.h \
		/usr/include/qt5/QtCore/qstack.h \
		/usr/include/qt5/QtCore/qstandardpaths.h \
		/usr/include/qt5/QtCore/qstate.h \
		/usr/include/qt5/QtCore/qstatemachine.h \
		/usr/include/qt5/QtCore/qstorageinfo.h \
		/usr/include/qt5/QtCore/qstringlistmodel.h \
		/usr/include/qt5/QtCore/qsystemsemaphore.h \
		/usr/include/qt5/QtCore/qtemporarydir.h \
		/usr/include/qt5/QtCore/qtemporaryfile.h \
		/usr/include/qt5/QtCore/qtextboundaryfinder.h \
		/usr/include/qt5/QtCore/qtextcodec.h \
		/usr/include/qt5/QtCore/qthread.h \
		/usr/include/qt5/QtCore/qthreadpool.h \
		/usr/include/qt5/QtCore/qthreadstorage.h \
		/usr/include/qt5/QtCore/qtimeline.h \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qtimezone.h \
		/usr/include/qt5/QtCore/qtranslator.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qwaitcondition.h \
		/usr/include/qt5/QtCore/qwineventnotifier.h \
		/usr/include/qt5/QtCore/qxmlstream.h \
		/usr/include/qt5/QtCore/qtcoreversion.h \
		/usr/include/qt5/QtGui/QtGui \
		/usr/include/qt5/QtGui/QtGuiDepends \
		/usr/include/qt5/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt5/QtGui/qtextlayout.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/include/qt5/QtGui/qglyphrun.h \
		/usr/include/qt5/QtGui/qrawfont.h \
		/usr/include/qt5/QtGui/qfontdatabase.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextdocument.h \
		/usr/include/qt5/QtGui/qaccessible.h \
		/usr/include/qt5/QtGui/qaccessiblebridge.h \
		/usr/include/qt5/QtGui/qaccessibleobject.h \
		/usr/include/qt5/QtGui/qaccessibleplugin.h \
		/usr/include/qt5/QtGui/qbackingstore.h \
		/usr/include/qt5/QtGui/qwindow.h \
		/usr/include/qt5/QtCore/QEvent \
		/usr/include/qt5/QtCore/QMargins \
		/usr/include/qt5/QtCore/QRect \
		/usr/include/qt5/QtGui/qsurface.h \
		/usr/include/qt5/QtGui/qsurfaceformat.h \
		/usr/include/qt5/QtGui/qbitmap.h \
		/usr/include/qt5/QtGui/qclipboard.h \
		/usr/include/qt5/QtGui/qdesktopservices.h \
		/usr/include/qt5/QtGui/qdrag.h \
		/usr/include/qt5/QtGui/qgenericmatrix.h \
		/usr/include/qt5/QtGui/qgenericplugin.h \
		/usr/include/qt5/QtGui/qgenericpluginfactory.h \
		/usr/include/qt5/QtGui/qiconengine.h \
		/usr/include/qt5/QtGui/qiconengineplugin.h \
		/usr/include/qt5/QtGui/qimageiohandler.h \
		/usr/include/qt5/QtGui/qimagereader.h \
		/usr/include/qt5/QtGui/qimagewriter.h \
		/usr/include/qt5/QtGui/qmatrix4x4.h \
		/usr/include/qt5/QtGui/qvector3d.h \
		/usr/include/qt5/QtGui/qvector4d.h \
		/usr/include/qt5/QtGui/qquaternion.h \
		/usr/include/qt5/QtGui/qmovie.h \
		/usr/include/qt5/QtGui/qoffscreensurface.h \
		/usr/include/qt5/QtGui/qopengl.h \
		/usr/include/qt5/QtCore/qt_windows.h \
		/usr/include/qt5/QtGui/qopengles2ext.h \
		/usr/include/qt5/QtGui/qopenglext.h \
		/usr/include/qt5/QtGui/qopenglbuffer.h \
		/usr/include/qt5/QtGui/qopenglcontext.h \
		/usr/include/qt5/QtCore/QScopedPointer \
		/usr/include/qt5/QtGui/QSurfaceFormat \
		/usr/include/qt5/QtGui/qopenglversionfunctions.h \
		/usr/include/qt5/QtGui/qopengldebug.h \
		/usr/include/qt5/QtGui/qopenglextrafunctions.h \
		/usr/include/qt5/QtGui/qopenglfunctions.h \
		/usr/include/qt5/QtGui/qopenglframebufferobject.h \
		/usr/include/qt5/QtGui/qopenglpaintdevice.h \
		/usr/include/qt5/QtGui/qopenglpixeltransferoptions.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtGui/qopenglshaderprogram.h \
		/usr/include/qt5/QtGui/qopengltexture.h \
		/usr/include/qt5/QtGui/qopengltextureblitter.h \
		/usr/include/qt5/QtGui/QMatrix3x3 \
		/usr/include/qt5/QtGui/QMatrix4x4 \
		/usr/include/qt5/QtGui/qopengltimerquery.h \
		/usr/include/qt5/QtGui/qopenglvertexarrayobject.h \
		/usr/include/qt5/QtGui/qopenglwindow.h \
		/usr/include/qt5/QtGui/QPaintDeviceWindow \
		/usr/include/qt5/QtGui/qpaintdevicewindow.h \
		/usr/include/qt5/QtGui/QWindow \
		/usr/include/qt5/QtGui/QPaintDevice \
		/usr/include/qt5/QtGui/QOpenGLContext \
		/usr/include/qt5/QtGui/QImage \
		/usr/include/qt5/QtGui/qpagedpaintdevice.h \
		/usr/include/qt5/QtGui/qpagelayout.h \
		/usr/include/qt5/QtGui/qpagesize.h \
		/usr/include/qt5/QtGui/qpaintengine.h \
		/usr/include/qt5/QtGui/qpainter.h \
		/usr/include/qt5/QtGui/qpdfwriter.h \
		/usr/include/qt5/QtGui/qpicture.h \
		/usr/include/qt5/QtGui/qpictureformatplugin.h \
		/usr/include/qt5/QtGui/qpixmapcache.h \
		/usr/include/qt5/QtGui/qrasterwindow.h \
		/usr/include/qt5/QtGui/qscreen.h \
		/usr/include/qt5/QtCore/QList \
		/usr/include/qt5/QtCore/QSize \
		/usr/include/qt5/QtCore/QSizeF \
		/usr/include/qt5/QtGui/QTransform \
		/usr/include/qt5/QtGui/qsessionmanager.h \
		/usr/include/qt5/QtGui/qstandarditemmodel.h \
		/usr/include/qt5/QtGui/qstatictext.h \
		/usr/include/qt5/QtGui/qstylehints.h \
		/usr/include/qt5/QtGui/qsyntaxhighlighter.h \
		/usr/include/qt5/QtGui/qtextobject.h \
		/usr/include/qt5/QtGui/qtextdocumentfragment.h \
		/usr/include/qt5/QtGui/qtextdocumentwriter.h \
		/usr/include/qt5/QtGui/qtextlist.h \
		/usr/include/qt5/QtGui/qtexttable.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtGui/qtguiversion.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtWidgets/qaccessiblewidget.h \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/qcalendarwidget.h \
		/usr/include/qt5/QtWidgets/qcheckbox.h \
		/usr/include/qt5/QtWidgets/qcolordialog.h \
		/usr/include/qt5/QtWidgets/qcolormap.h \
		/usr/include/qt5/QtWidgets/qcolumnview.h \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qcommandlinkbutton.h \
		/usr/include/qt5/QtWidgets/qpushbutton.h \
		/usr/include/qt5/QtWidgets/qcommonstyle.h \
		/usr/include/qt5/QtWidgets/qcompleter.h \
		/usr/include/qt5/QtWidgets/qdatawidgetmapper.h \
		/usr/include/qt5/QtWidgets/qdatetimeedit.h \
		/usr/include/qt5/QtWidgets/qdial.h \
		/usr/include/qt5/QtWidgets/qdialogbuttonbox.h \
		/usr/include/qt5/QtWidgets/qdirmodel.h \
		/usr/include/qt5/QtWidgets/qfileiconprovider.h \
		/usr/include/qt5/QtWidgets/qdockwidget.h \
		/usr/include/qt5/QtWidgets/qdrawutil.h \
		/usr/include/qt5/QtWidgets/qerrormessage.h \
		/usr/include/qt5/QtWidgets/qfiledialog.h \
		/usr/include/qt5/QtWidgets/qfilesystemmodel.h \
		/usr/include/qt5/QtWidgets/qfocusframe.h \
		/usr/include/qt5/QtWidgets/qfontcombobox.h \
		/usr/include/qt5/QtWidgets/qfontdialog.h \
		/usr/include/qt5/QtWidgets/qformlayout.h \
		/usr/include/qt5/QtWidgets/QLayout \
		/usr/include/qt5/QtWidgets/qgesture.h \
		/usr/include/qt5/QtWidgets/qgesturerecognizer.h \
		/usr/include/qt5/QtWidgets/qgraphicsanchorlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsitem.h \
		/usr/include/qt5/QtWidgets/qgraphicslayout.h \
		/usr/include/qt5/QtWidgets/qgraphicslayoutitem.h \
		/usr/include/qt5/QtWidgets/qgraphicseffect.h \
		/usr/include/qt5/QtWidgets/qgraphicsgridlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsitemanimation.h \
		/usr/include/qt5/QtWidgets/qgraphicslinearlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsproxywidget.h \
		/usr/include/qt5/QtWidgets/qgraphicswidget.h \
		/usr/include/qt5/QtWidgets/qgraphicsscene.h \
		/usr/include/qt5/QtWidgets/qgraphicssceneevent.h \
		/usr/include/qt5/QtWidgets/qgraphicstransform.h \
		/usr/include/qt5/QtGui/QVector3D \
		/usr/include/qt5/QtWidgets/qgraphicsview.h \
		/usr/include/qt5/QtWidgets/qscrollarea.h \
		/usr/include/qt5/QtWidgets/qgroupbox.h \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qinputdialog.h \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtWidgets/qitemdelegate.h \
		/usr/include/qt5/QtWidgets/qitemeditorfactory.h \
		/usr/include/qt5/QtWidgets/qkeyeventtransition.h \
		/usr/include/qt5/QtWidgets/qkeysequenceedit.h \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qlcdnumber.h \
		/usr/include/qt5/QtWidgets/qlistview.h \
		/usr/include/qt5/QtWidgets/qlistwidget.h \
		/usr/include/qt5/QtWidgets/qmdiarea.h \
		/usr/include/qt5/QtWidgets/qmdisubwindow.h \
		/usr/include/qt5/QtWidgets/qmouseeventtransition.h \
		/usr/include/qt5/QtWidgets/qopenglwidget.h \
		/usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qplaintextedit.h \
		/usr/include/qt5/QtWidgets/qtextedit.h \
		/usr/include/qt5/QtWidgets/qprogressbar.h \
		/usr/include/qt5/QtWidgets/qprogressdialog.h \
		/usr/include/qt5/QtWidgets/qproxystyle.h \
		/usr/include/qt5/QtWidgets/QCommonStyle \
		/usr/include/qt5/QtWidgets/qradiobutton.h \
		/usr/include/qt5/QtWidgets/qscrollbar.h \
		/usr/include/qt5/QtWidgets/qscroller.h \
		/usr/include/qt5/QtCore/QPointF \
		/usr/include/qt5/QtWidgets/QScrollerProperties \
		/usr/include/qt5/QtWidgets/qscrollerproperties.h \
		/usr/include/qt5/QtCore/QMetaType \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/qshortcut.h \
		/usr/include/qt5/QtWidgets/qsizegrip.h \
		/usr/include/qt5/QtWidgets/qspinbox.h \
		/usr/include/qt5/QtWidgets/qsplashscreen.h \
		/usr/include/qt5/QtWidgets/qsplitter.h \
		/usr/include/qt5/QtWidgets/qstackedlayout.h \
		/usr/include/qt5/QtWidgets/qstackedwidget.h \
		/usr/include/qt5/QtWidgets/qstatusbar.h \
		/usr/include/qt5/QtWidgets/qstyleditemdelegate.h \
		/usr/include/qt5/QtWidgets/qstylefactory.h \
		/usr/include/qt5/QtWidgets/qstylepainter.h \
		/usr/include/qt5/QtWidgets/qstyleplugin.h \
		/usr/include/qt5/QtWidgets/qsystemtrayicon.h \
		/usr/include/qt5/QtWidgets/qtableview.h \
		/usr/include/qt5/QtWidgets/qtablewidget.h \
		/usr/include/qt5/QtWidgets/qtextbrowser.h \
		/usr/include/qt5/QtWidgets/qtoolbar.h \
		/usr/include/qt5/QtWidgets/qtoolbox.h \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/qtooltip.h \
		/usr/include/qt5/QtWidgets/qtreeview.h \
		/usr/include/qt5/QtWidgets/qtreewidget.h \
		/usr/include/qt5/QtWidgets/qtreewidgetitemiterator.h \
		/usr/include/qt5/QtWidgets/qundogroup.h \
		/usr/include/qt5/QtWidgets/qundostack.h \
		/usr/include/qt5/QtWidgets/qundoview.h \
		/usr/include/qt5/QtWidgets/qwhatsthis.h \
		/usr/include/qt5/QtWidgets/qwidgetaction.h \
		/usr/include/qt5/QtWidgets/qwizard.h \
		/usr/include/qt5/QtWidgets/qtwidgetsversion.h \
		graphMethod.h \
		approximator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

approximator.o: approximator.cpp approximator.h \
		graphMethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o approximator.o approximator.cpp

window.o: window.cpp /usr/include/qt5/QtGui/QPainter \
		/usr/include/qt5/QtGui/qpainter.h \
		/usr/include/qt5/QtGui/qtguiglobal.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qconfig-64.h \
		/usr/include/qt5/QtCore/qtcore-config.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qnumeric.h \
		/usr/include/qt5/QtCore/qversiontagging.h \
		/usr/include/qt5/QtGui/qtgui-config.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qhashfunctions.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qstringliteral.h \
		/usr/include/qt5/QtCore/qstringalgorithms.h \
		/usr/include/qt5/QtCore/qstringview.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qbytearraylist.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qrgba64.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixelformat.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		window.h \
		/usr/include/qt5/QtWidgets/QtWidgets \
		/usr/include/qt5/QtWidgets/QtWidgetsDepends \
		/usr/include/qt5/QtCore/QtCore \
		/usr/include/qt5/QtCore/QtCoreDepends \
		/usr/include/qt5/QtCore/qabstractanimation.h \
		/usr/include/qt5/QtCore/qabstracteventdispatcher.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qabstractnativeeventfilter.h \
		/usr/include/qt5/QtCore/qabstractproxymodel.h \
		/usr/include/qt5/QtCore/qabstractstate.h \
		/usr/include/qt5/QtCore/qabstracttransition.h \
		/usr/include/qt5/QtCore/qanimationgroup.h \
		/usr/include/qt5/QtCore/qarraydataops.h \
		/usr/include/qt5/QtCore/qarraydatapointer.h \
		/usr/include/qt5/QtCore/qbasictimer.h \
		/usr/include/qt5/QtCore/qbitarray.h \
		/usr/include/qt5/QtCore/qbuffer.h \
		/usr/include/qt5/QtCore/qbytearraymatcher.h \
		/usr/include/qt5/QtCore/qcache.h \
		/usr/include/qt5/QtCore/qcborarray.h \
		/usr/include/qt5/QtCore/qcborvalue.h \
		/usr/include/qt5/QtCore/qdatetime.h \
		/usr/include/qt5/QtCore/qcborcommon.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/quuid.h \
		/usr/include/qt5/QtCore/qcbormap.h \
		/usr/include/qt5/QtCore/qcborstream.h \
		/usr/include/qt5/QtCore/qfloat16.h \
		/usr/include/qt5/QtCore/qcollator.h \
		/usr/include/qt5/QtCore/qcommandlineoption.h \
		/usr/include/qt5/QtCore/qcommandlineparser.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qcryptographichash.h \
		/usr/include/qt5/QtCore/qdeadlinetimer.h \
		/usr/include/qt5/QtCore/qelapsedtimer.h \
		/usr/include/qt5/QtCore/qdir.h \
		/usr/include/qt5/QtCore/qfileinfo.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtCore/qdiriterator.h \
		/usr/include/qt5/QtCore/qeasingcurve.h \
		/usr/include/qt5/QtCore/qendian.h \
		/usr/include/qt5/QtCore/qeventtransition.h \
		/usr/include/qt5/QtCore/qexception.h \
		/usr/include/qt5/QtCore/qfactoryinterface.h \
		/usr/include/qt5/QtCore/qfileselector.h \
		/usr/include/qt5/QtCore/QObject \
		/usr/include/qt5/QtCore/QStringList \
		/usr/include/qt5/QtCore/qfilesystemwatcher.h \
		/usr/include/qt5/QtCore/qfinalstate.h \
		/usr/include/qt5/QtCore/qfuture.h \
		/usr/include/qt5/QtCore/qfutureinterface.h \
		/usr/include/qt5/QtCore/qrunnable.h \
		/usr/include/qt5/QtCore/qresultstore.h \
		/usr/include/qt5/QtCore/qfuturesynchronizer.h \
		/usr/include/qt5/QtCore/qfuturewatcher.h \
		/usr/include/qt5/QtCore/qhistorystate.h \
		/usr/include/qt5/QtCore/qidentityproxymodel.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtCore/qjsonarray.h \
		/usr/include/qt5/QtCore/qjsonvalue.h \
		/usr/include/qt5/QtCore/qjsondocument.h \
		/usr/include/qt5/QtCore/qjsonobject.h \
		/usr/include/qt5/QtCore/qlibrary.h \
		/usr/include/qt5/QtCore/qlibraryinfo.h \
		/usr/include/qt5/QtCore/qversionnumber.h \
		/usr/include/qt5/QtCore/qlinkedlist.h \
		/usr/include/qt5/QtCore/qlockfile.h \
		/usr/include/qt5/QtCore/qloggingcategory.h \
		/usr/include/qt5/QtCore/qmath.h \
		/usr/include/qt5/QtCore/qmessageauthenticationcode.h \
		/usr/include/qt5/QtCore/qmetaobject.h \
		/usr/include/qt5/QtCore/qmimedata.h \
		/usr/include/qt5/QtCore/qmimedatabase.h \
		/usr/include/qt5/QtCore/qmimetype.h \
		/usr/include/qt5/QtCore/qobjectcleanuphandler.h \
		/usr/include/qt5/QtCore/qoperatingsystemversion.h \
		/usr/include/qt5/QtCore/qparallelanimationgroup.h \
		/usr/include/qt5/QtCore/qpauseanimation.h \
		/usr/include/qt5/QtCore/qplugin.h \
		/usr/include/qt5/QtCore/qpointer.h \
		/usr/include/qt5/QtCore/qpluginloader.h \
		/usr/include/qt5/QtCore/qprocess.h \
		/usr/include/qt5/QtCore/qpropertyanimation.h \
		/usr/include/qt5/QtCore/qvariantanimation.h \
		/usr/include/qt5/QtCore/qqueue.h \
		/usr/include/qt5/QtCore/qrandom.h \
		/usr/include/qt5/QtCore/qreadwritelock.h \
		/usr/include/qt5/QtCore/qresource.h \
		/usr/include/qt5/QtCore/qsavefile.h \
		/usr/include/qt5/QtCore/qscopedvaluerollback.h \
		/usr/include/qt5/QtCore/qscopeguard.h \
		/usr/include/qt5/QtCore/qsemaphore.h \
		/usr/include/qt5/QtCore/qsequentialanimationgroup.h \
		/usr/include/qt5/QtCore/qsettings.h \
		/usr/include/qt5/QtCore/qsharedmemory.h \
		/usr/include/qt5/QtCore/qsignalmapper.h \
		/usr/include/qt5/QtCore/qsignaltransition.h \
		/usr/include/qt5/QtCore/qsocketnotifier.h \
		/usr/include/qt5/QtCore/qsortfilterproxymodel.h \
		/usr/include/qt5/QtCore/qstack.h \
		/usr/include/qt5/QtCore/qstandardpaths.h \
		/usr/include/qt5/QtCore/qstate.h \
		/usr/include/qt5/QtCore/qstatemachine.h \
		/usr/include/qt5/QtCore/qstorageinfo.h \
		/usr/include/qt5/QtCore/qstringlistmodel.h \
		/usr/include/qt5/QtCore/qsystemsemaphore.h \
		/usr/include/qt5/QtCore/qtemporarydir.h \
		/usr/include/qt5/QtCore/qtemporaryfile.h \
		/usr/include/qt5/QtCore/qtextboundaryfinder.h \
		/usr/include/qt5/QtCore/qtextcodec.h \
		/usr/include/qt5/QtCore/qthread.h \
		/usr/include/qt5/QtCore/qthreadpool.h \
		/usr/include/qt5/QtCore/qthreadstorage.h \
		/usr/include/qt5/QtCore/qtimeline.h \
		/usr/include/qt5/QtCore/qtimer.h \
		/usr/include/qt5/QtCore/qtimezone.h \
		/usr/include/qt5/QtCore/qtranslator.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qwaitcondition.h \
		/usr/include/qt5/QtCore/qwineventnotifier.h \
		/usr/include/qt5/QtCore/qxmlstream.h \
		/usr/include/qt5/QtCore/qtcoreversion.h \
		/usr/include/qt5/QtGui/QtGui \
		/usr/include/qt5/QtGui/QtGuiDepends \
		/usr/include/qt5/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt5/QtGui/qtextlayout.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qglyphrun.h \
		/usr/include/qt5/QtGui/qrawfont.h \
		/usr/include/qt5/QtGui/qfontdatabase.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextdocument.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qaccessible.h \
		/usr/include/qt5/QtGui/qaccessiblebridge.h \
		/usr/include/qt5/QtGui/qaccessibleobject.h \
		/usr/include/qt5/QtGui/qaccessibleplugin.h \
		/usr/include/qt5/QtGui/qbackingstore.h \
		/usr/include/qt5/QtGui/qwindow.h \
		/usr/include/qt5/QtCore/QEvent \
		/usr/include/qt5/QtCore/QMargins \
		/usr/include/qt5/QtCore/QRect \
		/usr/include/qt5/QtGui/qsurface.h \
		/usr/include/qt5/QtGui/qsurfaceformat.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qbitmap.h \
		/usr/include/qt5/QtGui/qclipboard.h \
		/usr/include/qt5/QtGui/qdesktopservices.h \
		/usr/include/qt5/QtGui/qdrag.h \
		/usr/include/qt5/QtGui/qgenericmatrix.h \
		/usr/include/qt5/QtGui/qgenericplugin.h \
		/usr/include/qt5/QtGui/qgenericpluginfactory.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtGui/qiconengine.h \
		/usr/include/qt5/QtGui/qiconengineplugin.h \
		/usr/include/qt5/QtGui/qimageiohandler.h \
		/usr/include/qt5/QtGui/qimagereader.h \
		/usr/include/qt5/QtGui/qimagewriter.h \
		/usr/include/qt5/QtGui/qmatrix4x4.h \
		/usr/include/qt5/QtGui/qvector3d.h \
		/usr/include/qt5/QtGui/qvector4d.h \
		/usr/include/qt5/QtGui/qquaternion.h \
		/usr/include/qt5/QtGui/qmovie.h \
		/usr/include/qt5/QtGui/qoffscreensurface.h \
		/usr/include/qt5/QtGui/qopengl.h \
		/usr/include/qt5/QtCore/qt_windows.h \
		/usr/include/qt5/QtGui/qopengles2ext.h \
		/usr/include/qt5/QtGui/qopenglext.h \
		/usr/include/qt5/QtGui/qopenglbuffer.h \
		/usr/include/qt5/QtGui/qopenglcontext.h \
		/usr/include/qt5/QtCore/QScopedPointer \
		/usr/include/qt5/QtGui/QSurfaceFormat \
		/usr/include/qt5/QtGui/qopenglversionfunctions.h \
		/usr/include/qt5/QtGui/qopengldebug.h \
		/usr/include/qt5/QtGui/qopenglextrafunctions.h \
		/usr/include/qt5/QtGui/qopenglfunctions.h \
		/usr/include/qt5/QtGui/qopenglframebufferobject.h \
		/usr/include/qt5/QtGui/qopenglpaintdevice.h \
		/usr/include/qt5/QtGui/qopenglpixeltransferoptions.h \
		/usr/include/qt5/QtCore/QSharedDataPointer \
		/usr/include/qt5/QtGui/qopenglshaderprogram.h \
		/usr/include/qt5/QtGui/qopengltexture.h \
		/usr/include/qt5/QtGui/qopengltextureblitter.h \
		/usr/include/qt5/QtGui/QMatrix3x3 \
		/usr/include/qt5/QtGui/QMatrix4x4 \
		/usr/include/qt5/QtGui/qopengltimerquery.h \
		/usr/include/qt5/QtGui/qopenglvertexarrayobject.h \
		/usr/include/qt5/QtGui/qopenglwindow.h \
		/usr/include/qt5/QtGui/QPaintDeviceWindow \
		/usr/include/qt5/QtGui/qpaintdevicewindow.h \
		/usr/include/qt5/QtGui/QWindow \
		/usr/include/qt5/QtGui/QPaintDevice \
		/usr/include/qt5/QtGui/QOpenGLContext \
		/usr/include/qt5/QtGui/QImage \
		/usr/include/qt5/QtGui/qpagedpaintdevice.h \
		/usr/include/qt5/QtGui/qpagelayout.h \
		/usr/include/qt5/QtGui/qpagesize.h \
		/usr/include/qt5/QtGui/qpaintengine.h \
		/usr/include/qt5/QtGui/qpdfwriter.h \
		/usr/include/qt5/QtGui/qpicture.h \
		/usr/include/qt5/QtGui/qpictureformatplugin.h \
		/usr/include/qt5/QtGui/qpixmapcache.h \
		/usr/include/qt5/QtGui/qrasterwindow.h \
		/usr/include/qt5/QtGui/qscreen.h \
		/usr/include/qt5/QtCore/QList \
		/usr/include/qt5/QtCore/QSize \
		/usr/include/qt5/QtCore/QSizeF \
		/usr/include/qt5/QtGui/QTransform \
		/usr/include/qt5/QtGui/qsessionmanager.h \
		/usr/include/qt5/QtGui/qstandarditemmodel.h \
		/usr/include/qt5/QtGui/qstatictext.h \
		/usr/include/qt5/QtGui/qstylehints.h \
		/usr/include/qt5/QtGui/qsyntaxhighlighter.h \
		/usr/include/qt5/QtGui/qtextobject.h \
		/usr/include/qt5/QtGui/qtextdocumentfragment.h \
		/usr/include/qt5/QtGui/qtextdocumentwriter.h \
		/usr/include/qt5/QtGui/qtextlist.h \
		/usr/include/qt5/QtGui/qtexttable.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtGui/qtguiversion.h \
		/usr/include/qt5/QtWidgets/qtwidgetsglobal.h \
		/usr/include/qt5/QtWidgets/qtwidgets-config.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtWidgets/qaccessiblewidget.h \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/qcalendarwidget.h \
		/usr/include/qt5/QtWidgets/qcheckbox.h \
		/usr/include/qt5/QtWidgets/qcolordialog.h \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/qcolormap.h \
		/usr/include/qt5/QtWidgets/qcolumnview.h \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qcommandlinkbutton.h \
		/usr/include/qt5/QtWidgets/qpushbutton.h \
		/usr/include/qt5/QtWidgets/qcommonstyle.h \
		/usr/include/qt5/QtWidgets/qcompleter.h \
		/usr/include/qt5/QtWidgets/qdatawidgetmapper.h \
		/usr/include/qt5/QtWidgets/qdatetimeedit.h \
		/usr/include/qt5/QtWidgets/qdial.h \
		/usr/include/qt5/QtWidgets/qdialogbuttonbox.h \
		/usr/include/qt5/QtWidgets/qdirmodel.h \
		/usr/include/qt5/QtWidgets/qfileiconprovider.h \
		/usr/include/qt5/QtWidgets/qdockwidget.h \
		/usr/include/qt5/QtWidgets/qdrawutil.h \
		/usr/include/qt5/QtWidgets/qerrormessage.h \
		/usr/include/qt5/QtWidgets/qfiledialog.h \
		/usr/include/qt5/QtWidgets/qfilesystemmodel.h \
		/usr/include/qt5/QtWidgets/qfocusframe.h \
		/usr/include/qt5/QtWidgets/qfontcombobox.h \
		/usr/include/qt5/QtWidgets/qfontdialog.h \
		/usr/include/qt5/QtWidgets/qformlayout.h \
		/usr/include/qt5/QtWidgets/QLayout \
		/usr/include/qt5/QtWidgets/qgesture.h \
		/usr/include/qt5/QtWidgets/qgesturerecognizer.h \
		/usr/include/qt5/QtWidgets/qgraphicsanchorlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsitem.h \
		/usr/include/qt5/QtWidgets/qgraphicslayout.h \
		/usr/include/qt5/QtWidgets/qgraphicslayoutitem.h \
		/usr/include/qt5/QtWidgets/qgraphicseffect.h \
		/usr/include/qt5/QtWidgets/qgraphicsgridlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsitemanimation.h \
		/usr/include/qt5/QtWidgets/qgraphicslinearlayout.h \
		/usr/include/qt5/QtWidgets/qgraphicsproxywidget.h \
		/usr/include/qt5/QtWidgets/qgraphicswidget.h \
		/usr/include/qt5/QtWidgets/qgraphicsscene.h \
		/usr/include/qt5/QtWidgets/qgraphicssceneevent.h \
		/usr/include/qt5/QtWidgets/qgraphicstransform.h \
		/usr/include/qt5/QtGui/QVector3D \
		/usr/include/qt5/QtWidgets/qgraphicsview.h \
		/usr/include/qt5/QtWidgets/qscrollarea.h \
		/usr/include/qt5/QtWidgets/qgroupbox.h \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qinputdialog.h \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtWidgets/qitemdelegate.h \
		/usr/include/qt5/QtWidgets/qitemeditorfactory.h \
		/usr/include/qt5/QtWidgets/qkeyeventtransition.h \
		/usr/include/qt5/QtWidgets/qkeysequenceedit.h \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/qlcdnumber.h \
		/usr/include/qt5/QtWidgets/qlistview.h \
		/usr/include/qt5/QtWidgets/qlistwidget.h \
		/usr/include/qt5/QtWidgets/qmainwindow.h \
		/usr/include/qt5/QtWidgets/qmdiarea.h \
		/usr/include/qt5/QtWidgets/qmdisubwindow.h \
		/usr/include/qt5/QtWidgets/qmenu.h \
		/usr/include/qt5/QtWidgets/qmenubar.h \
		/usr/include/qt5/QtWidgets/qmessagebox.h \
		/usr/include/qt5/QtWidgets/qmouseeventtransition.h \
		/usr/include/qt5/QtWidgets/qopenglwidget.h \
		/usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qplaintextedit.h \
		/usr/include/qt5/QtWidgets/qtextedit.h \
		/usr/include/qt5/QtWidgets/qprogressbar.h \
		/usr/include/qt5/QtWidgets/qprogressdialog.h \
		/usr/include/qt5/QtWidgets/qproxystyle.h \
		/usr/include/qt5/QtWidgets/QCommonStyle \
		/usr/include/qt5/QtWidgets/qradiobutton.h \
		/usr/include/qt5/QtWidgets/qscrollbar.h \
		/usr/include/qt5/QtWidgets/qscroller.h \
		/usr/include/qt5/QtCore/QPointF \
		/usr/include/qt5/QtWidgets/QScrollerProperties \
		/usr/include/qt5/QtWidgets/qscrollerproperties.h \
		/usr/include/qt5/QtCore/QMetaType \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/qshortcut.h \
		/usr/include/qt5/QtWidgets/qsizegrip.h \
		/usr/include/qt5/QtWidgets/qspinbox.h \
		/usr/include/qt5/QtWidgets/qsplashscreen.h \
		/usr/include/qt5/QtWidgets/qsplitter.h \
		/usr/include/qt5/QtWidgets/qstackedlayout.h \
		/usr/include/qt5/QtWidgets/qstackedwidget.h \
		/usr/include/qt5/QtWidgets/qstatusbar.h \
		/usr/include/qt5/QtWidgets/qstyleditemdelegate.h \
		/usr/include/qt5/QtWidgets/qstylefactory.h \
		/usr/include/qt5/QtWidgets/qstylepainter.h \
		/usr/include/qt5/QtWidgets/qstyleplugin.h \
		/usr/include/qt5/QtWidgets/qsystemtrayicon.h \
		/usr/include/qt5/QtWidgets/qtableview.h \
		/usr/include/qt5/QtWidgets/qtablewidget.h \
		/usr/include/qt5/QtWidgets/qtextbrowser.h \
		/usr/include/qt5/QtWidgets/qtoolbar.h \
		/usr/include/qt5/QtWidgets/qtoolbox.h \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/qtooltip.h \
		/usr/include/qt5/QtWidgets/qtreeview.h \
		/usr/include/qt5/QtWidgets/qtreewidget.h \
		/usr/include/qt5/QtWidgets/qtreewidgetitemiterator.h \
		/usr/include/qt5/QtWidgets/qundogroup.h \
		/usr/include/qt5/QtWidgets/qundostack.h \
		/usr/include/qt5/QtWidgets/qundoview.h \
		/usr/include/qt5/QtWidgets/qwhatsthis.h \
		/usr/include/qt5/QtWidgets/qwidgetaction.h \
		/usr/include/qt5/QtWidgets/qwizard.h \
		/usr/include/qt5/QtWidgets/qtwidgetsversion.h \
		graphMethod.h \
		approximator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

